export enum TypeSpecialiste{
    SPECIALISTE_SECHERESSE,
    SPECIALISTE_INONDATION,
    PHYTOPATHOLOGUE    ,
    ENTOMOLOGUE,
    PEDOLOGUE,
    IRRIGATIONISTE,
    AGROCHIMISTE,
    METEOROLOGUE_AGRICOLE
}